### ISSUE TITLE
De-ES6ify and promise support

### ISSUE THREAD

**Issue by blakeembrey** [m0ppers/promise-any#3]
Would you consider supporting non-ES6 clients (no iterator spread) and use a module like `any-promise` so people can fallback on any promise library? For anyone currently using the library, there'd be zero functionality change, but this would allow it to work in projects currently supporting older node/browser versions.

**Comment by m0ppers** [comment]
To be honest I like it to be ES6 only. However I must admit that I am unsure what is going out there as I am currently not doing much JS development. My last impression was that the node community would upgrade relatively quickly and that people targeting browser environments with their applications would have a build process incorporating a transpiler anyway.

The library currently has zero dependencies and very few LOC which I really like. What would really feel awkward would be `promise-any` requiring `any-promise` 🐔 . What do you think?

**Comment by blakeembrey** [comment]
It's really up to you. In most places I still support node 0.10 clients and I know some node 0.10 clients are still using those modules. It's so few lines of code to de-ES6ify it, that it's very simple and wouldn't greatly impact the build-size.

On the browser transpilation side, I don't think it's entirely accurate. For instance, Browserify is local transforms by default. This can result in someone using the module with Browserify and having it work until someone happens to load it on an older browser. Personally, I just incorporate the transpiler in my toolchain and compile for the lowest common denominator (which is pretty much node 0.10) so people don't have to do that themselves. 

Again, it's a personal choice. I know a few people have pushed quickly to newer versions and with those modules I'm stuck pinned to an older version.

**Comment by m0ppers** [comment]
I think I will stick to the ES6 variant for now :) Maybe if there is more interest :)

**Comment by blakeembrey** [comment]
Ok, that's a bummer 😦 Guess I'll be have to copy the source inline for now or re-publish it a another name.
